version: '2.2'
services:
  appdyntest-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    restart: always
    container_name: appdyntest-sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yourStrong(!)Password'
      MSSQL_PID: 'Express'
    ports:
      - 1433:1433
  appdyntest-frontend:
    build: ./AppdynTestFrontend
    restart: always
    container_name: appdyntest-frontend
    ports:
      - 80:80
  appdyntest-backend:
    build: ./AppDynTestBackend
    restart: always
    container_name: appdyntest-backend
    ports:
      - 9080:80
    environment: 
      CORECLR_PROFILER: "{57e1aa68-2229-41aa-9931-a6e93bbc64d8}"
      CORECLR_ENABLE_PROFILING: "1"
      CORECLR_PROFILER_PATH: "/opt/temp/libappdprofiler.so"
      LD_LIBRARY_PATH: "/opt/temp"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "AppdynTestBackend_name"
      APPDYNAMICS_AGENT_TIER_NAME: "AppdynTestBackend_tier"
      APPDYNAMICS_AGENT_NODE_NAME: "AppdynTestBackend_node"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "myorganization-test"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "<mypassword>"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "appdynamics.callofthevoid.dk"
      APPDYNAMICS_CONTROLLER_PORT: "8181"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
      APPDYNAMICS_CONTROLLER_SSL_CERTFILE: "/usr/local/share/ca-certificates/my-root.crt"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: "AppdynTestBackend_"
