version: '2.2'
services:
  appdyntest-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    restart: always
    container_name: appdyntest-sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yourStrong(!)Password'
      MSSQL_PID: 'Express'
    ports:
      - 1433:1433
  appdyntest-frontend:
    build: ./AppdynTestFrontend
    restart: always
    container_name: appdyntest-frontend
    ports:
      - 80:80
      - 443:443
  appdyntest-backend:
    build: ./AppDynTestBackend
    restart: always
    container_name: appdyntest-backend
    ports:
      - 8080:80
      - 4443:443